language: node_js

node_js:
  - "5.6"
  - "4.3"

before_install:
  - npm install -g eslint
  - npm install -g eslint-config-google
  - npm install -g eslint-config-xo

after_success:
  - eslint index.js